#!/bin/bash

NAME="CBL_App"
FLASKDIR=/app
VENVDIR=/home/jark/.virtualenvs/cbl
VENVNM=cbl
SOCKFILE=/app/sock
USER=jark
GROUP=jark
NUM_WORKERS=3

echo "Starting $NAME"

#activate virtualenv
source /usr/local/bin/virtualenvwrapper.sh
workon $VENVNM

export PYTHONPATH=$FLASKDIR:$PYTHONPATH

# create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# start gunicorn
exec gunicorn app:app -b 127.0.0.1:8000 \
    --name $NAME \
    --workers $NUM_WORKERS \
    --user=$USER --group=$GROUP \
    --log-level=debug
    --bind=unix:$SOCKFILE