"""initial migration

Revision ID: 48a7042b25d9
Revises: None
Create Date: 2014-06-11 23:20:23.574067

"""

# revision identifiers, used by Alembic.
revision = '48a7042b25d9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
